# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#

title: My Jekyll Site
email: your-email@example.com
description: >-
  A simple blog powered by Jekyll.

baseurl: "" # the subpath of your site, e.g., /blog
url: "http://example.com" # the base hostname & protocol for your site
github_username: your-github-username

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
